"""Add CompanyFact and evidence scores

Revision ID: 29d4c40233a6
Revises: be372e0d3301
Create Date: 2026-07-16 15:43:00.518736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d4c40233a6'
down_revision: Union[str, Sequence[str], None] = 'be372e0d3301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fact_name', sa.String(), nullable=False),
    sa.Column('fact_value', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_facts_fact_name'), 'company_facts', ['fact_name'], unique=False)
    op.create_index(op.f('ix_company_facts_id'), 'company_facts', ['id'], unique=False)
    op.add_column('performance_metrics', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('performance_metrics', sa.Column('evidence_summary', sa.JSON(), nullable=True))
    op.add_column('seo_data', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('seo_data', sa.Column('evidence_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seo_data', 'evidence_summary')
    op.drop_column('seo_data', 'confidence_score')
    op.drop_column('performance_metrics', 'evidence_summary')
    op.drop_column('performance_metrics', 'confidence_score')
    op.drop_index(op.f('ix_company_facts_id'), table_name='company_facts')
    op.drop_index(op.f('ix_company_facts_fact_name'), table_name='company_facts')
    op.drop_table('company_facts')
    # ### end Alembic commands ###
