from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
import json
import redis
from backend.core.config import settings

router = APIRouter()
redis_client = redis.from_url(settings.REDIS_URL)

@router.get("/{report_id}/csv")
def export_report_csv(report_id: str):
    """
    Export the AI report as a CSV string (Mocked for now).
    """
    report_data = redis_client.get(f"report_data:{report_id}")
    if not report_data:
        raise HTTPException(status_code=404, detail="Report not found")
        
    report = json.loads(report_data)
    
    csv_content = "Category,Item\n"
    csv_content += f"Company,{report['company']['name']}\n"
    csv_content += f"Domain,{report['company']['domain']}\n"
    
    for strength in report['analysis']['swot']['strengths']:
        csv_content += f"Strength,{strength}\n"
        
    for weakness in report['analysis']['swot']['weaknesses']:
        csv_content += f"Weakness,{weakness}\n"
        
    for pain in report['analysis']['pain_points']:
        csv_content += f"Pain Point,\"{pain['problem']} - {pain['evidence']}\"\n"
        
    return Response(content=csv_content, media_type="text/csv", headers={"Content-Disposition": f"attachment; filename=report_{report_id}.csv"})

from fastapi import Depends
from sqlalchemy.orm import Session
from backend.db.database import get_db
from backend.models.models import Company, PainPoint, Opportunity, Competitor
from fpdf import FPDF
import io

@router.get("/{company_id}/pitch-deck")
def export_pitch_deck(company_id: int, db: Session = Depends(get_db)):
    company = db.query(Company).filter(Company.id == company_id).first()
    if not company:
        raise HTTPException(status_code=404, detail="Company not found")
        
    pain_points = db.query(PainPoint).filter(PainPoint.company_id == company_id).limit(5).all()
    opportunities = db.query(Opportunity).filter(Opportunity.company_id == company_id).limit(5).all()
    competitors = db.query(Competitor).filter(Competitor.company_id == company_id).limit(3).all()
    
    pdf = FPDF()
    
    # Title Slide
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 60, "", 0, 1, "C")
    pdf.cell(0, 10, f"Strategic Pitch Deck:", 0, 1, "C")
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(25, 118, 210)
    pdf.cell(0, 20, f"{company.name}", 0, 1, "C")
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "Generated by AI Sales Agent", 0, 1, "C")
    
    # Pain Points Slide
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "Key Challenges & Pain Points", 0, 1, "L")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 12)
    for pp in pain_points:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"- {pp.title} ({pp.severity})", 0, 1, "L")
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 6, pp.description)
        pdf.ln(4)
        
    # Opportunities Slide
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "Strategic Opportunities", 0, 1, "L")
    pdf.ln(10)
    for opp in opportunities:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"- {opp.title} [{opp.type}]", 0, 1, "L")
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 6, opp.description)
        pdf.ln(4)
        
    # Competitor Landscape Slide
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "Competitor Landscape", 0, 1, "L")
    pdf.ln(10)
    for comp in competitors:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"- {comp.competitor_name}", 0, 1, "L")
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 6, f"Positioning: {comp.positioning}")
        pdf.ln(4)
        
    # Output PDF
    pdf_bytes = pdf.output()
    # Ensure it's returned as bytes
    if isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode('latin-1')
    
    return Response(content=bytes(pdf_bytes), media_type="application/pdf", headers={
        "Content-Disposition": f"attachment; filename={company.name.replace(' ', '_')}_Pitch_Deck.pdf"
    })
